language: generic 
sudo: required
services:
        - docker

before_install:
        - docker build -t sakhawat/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true sakhawat/docker-react npm test -- --coverege       
